# RocketMQ Broker 配置（演示环境，US-E1-01）
brokerClusterName = TradeGuardCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC
flushDiskType = ASYNC
# 演示环境自动建 Topic（case-events）；生产改为预建 + 白名单
autoCreateTopicEnable = true
autoCreateSubscriptionGroup = true
